version: "3"
services:
  client:
    image: "pmagas/multi-client-19-49"
    mem_limit: 128m
    hostname: client
  server:
    image: "pmagas/multi-server-19-49"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "pmagas/multi-worker-19-49"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "pmagas/multi-nginx-19-49"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
